apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-v1
  labels:
    app: todo-backend-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-v1
      version: v1
  template:
    metadata:
      labels:
        app: todo-backend-v1
        version: v1
    spec:
      containers:
      - name: nucknuck/todo-backend-v1
        image: todo-backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 4000 
          name: http
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-v1
spec:
  selector:
    app: todo-backend-v1
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000