apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v3
  labels:
    app: hello
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v3
  template:
    metadata:
      labels:
        app: hello
        version: v3
    spec:
      containers:
      - name: hello-v3
        image: nucknuck/hello:latest
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: v3
        ports:
        - containerPort: 8080
          name: http
        resources: {}