apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      version: v1
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: http
        volumeMounts:
          - mountPath: /data/db
            name: data-volume
        resources: {}
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017